### ISSUE TITLE
Apm is not defined

### ISSUE THREAD

**Issue by JackAdams** [arunoda/meteor-apm-client#1]
I followed the instructions in the Getting Started section, but got this when starting my app:

ReferenceError: Apm is not defined at app/server/apm.js:2:3

Not sure if the package has installed everything correctly (see image), as the content of the github repo looks quite different to anything I can find in my app.

![screen shot 2014-01-24 at 5 08 31 pm](https://f.cloud.github.com/assets/1647779/1993305/3407d148-84d7-11e3-8ea4-e93c84269154.png)

**Comment by arunoda** [comment]
you might need to do, `meteor add apm`.

May be your mrt version is bit old. (not sure though)

**Comment by JackAdams** [comment]
meteor add apm didn't work (apm: no such package), but I installed the latest version of meteorite and reinstalled apm and things are up and running now (well, not quite, but I'll open a separate issue for that).

**Comment by arunoda** [comment]
Yes. please do that.

On Sat, Jan 25, 2014 at 5:47 AM, Brent Abrahams notifications@github.comwrote:

> Closed #1 https://github.com/arunoda/meteor-apm-client/issues/1.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/arunoda/meteor-apm-client/issues/1
> .

## 

Arunoda Susiripala

@arunoda http://twitter.com/arunoda
http://gplus.to/arunodahttps://github.com/arunoda
http://www.linkedin.com/in/arunoda
