### ISSUE TITLE
[server] HighCharts horizontal axis duplicates days for short intervals

### ISSUE THREAD

**Issue by dandv** [arunoda/meteor-apm-client#12]
If the interval for accumulated data is shorter than a week, it would help to see timestamps in the chart, vs. the day repeated a several times.

![image](https://f.cloud.github.com/assets/33569/2364505/02149fa4-a679-11e3-84da-5007ea42896a.png)

I don't see the server code in the repo, but I think there's an issue with setting the `formatter` function on `xAsis.labels`. If you remove that function, HighCharts should dynamically display dates and times correctly.

**Comment by arunoda** [comment]
Thanks Dan for this and we'll work on this. 

BTW: Our server code is not available to the public since APM is not a open source project. But our client code for will be available openly but we've not decided about the license yet!

**Comment by arunoda** [comment]
Hi, 

We've fixed this. You won't be seeing something like this anymore.
Now if there is no data, we'll be padding them with zeros. That makes the graphs consistent.

**Comment by dandv** [comment]
Confirm fixed. Thanks!
