### ISSUE TITLE
Display "0" instead of no data for Methods?

### ISSUE THREAD

**Issue by dandv** [arunoda/meteor-apm-client#16]
I like the fix for issue #12, displaying a value of zero / flatline chart. Maybe zero would look better for other elements that currently display "No data". I think that "No data" suggests to the user there might have been an error connecting (e.g. issue #10), while zeros would just indicate that monitoring works, but the number of method calls for the past 30 minutes had just been zero.

**Comment by arunoda** [comment]
Good idea.

**Comment by arunoda** [comment]
We pushed a new change to do this, but only for time series charts.

**Comment by dandv** [comment]
Closing as fixed.
