### ISSUE TITLE
APM: Error sending payload(dropped after 5 tries)  getaddrinfo ENOTFOUND

### ISSUE THREAD

**Issue by JackAdams** [arunoda/meteor-apm-client#2]
Any ideas why I might be getting this message in my server console? (I'm trying to run apm on my local machine.)

**Comment by arunoda** [comment]
This may cause, when you internet connection cannot connect to our APM engine located at: https://engine.meteorapm.com

**Comment by JackAdams** [comment]
Yep something like that.  I turned a VPN on and the message has stopped appearing and the UI in "https://ui.meteorapm.com/apps/<my-app-id>/methods/overview" has updated, but no numbers showing yet (after about 6 minutes).

**Comment by arunoda** [comment]
you mean, nothing comes on the UI?

On Sat, Jan 25, 2014 at 5:59 AM, Brent Abrahams notifications@github.comwrote:

> Yep something like that. I turned a VPN on and the message has stopped
> appearing and the UI in https://ui.meteorapm.com/apps//methods/overview
> has updated, but no numbers showing yet (after about 6 minutes).
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/arunoda/meteor-apm-client/issues/2#issuecomment-33274788
> .

## 

Arunoda Susiripala

@arunoda http://twitter.com/arunoda
http://gplus.to/arunodahttps://github.com/arunoda
http://www.linkedin.com/in/arunoda

**Comment by JackAdams** [comment]
sorry -- I'm a fool!  I forgot to play around with my app a bit.  Everything is working fine now.  This is awesome!

**Comment by arunoda** [comment]
Ha ha :)

On Sat, Jan 25, 2014 at 6:02 AM, Brent Abrahams notifications@github.comwrote:

> Closed #2 https://github.com/arunoda/meteor-apm-client/issues/2.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/arunoda/meteor-apm-client/issues/2
> .

## 

Arunoda Susiripala

@arunoda http://twitter.com/arunoda
http://gplus.to/arunodahttps://github.com/arunoda
http://www.linkedin.com/in/arunoda
