### ISSUE TITLE
APM: Error sending payload

### ISSUE THREAD

**Issue by mitar** [arunoda/meteor-apm-client#22]
I am getting the following error:

```
APM: Error sending payload(dropped after 5 tries)  failed [413] Error: request entity too large at makeError (/app/node_modules/connect/node_modules/raw-body/index.js:132:15) at /app/node_modules/connect/node_modules/raw-bod...
```

**Comment by arunoda** [comment]
Hmm.

Seems like this is the issue: http://stackoverflow.com/a/19965089/457224
BTW: Can you please send me an email with your appId. We'll take the conversation on emails.

**Comment by arunoda** [comment]
BTW: Are you getting this error a lot or just once?

**Comment by mitar** [comment]
I am not yet using APM a lot, but it seems that I get it regularly.

**Comment by arunoda** [comment]
Yes, possible if you are doing lot of work inside a method or publication.
I need to find some solution.

---

Arunoda Susiripala

@arunoda http://twitter.com/arunoda
http://gplus.to/arunodahttps://github.com/arunoda
http://www.linkedin.com/in/arunoda

**Comment by mitar** [comment]
(I sent @arunoda privately more information and local logs.)

**Comment by arunoda** [comment]
Thanks.

---

Arunoda Susiripala

@arunoda http://twitter.com/arunoda
 http://gplus.to/arunodahttps://github.com/arunoda
http://www.linkedin.com/in/arunoda

**Comment by arunoda** [comment]
I hope, we can close this :)
