### ISSUE TITLE
Exception while invoking method 'getAddress' TypeError: Cannot read property 'statusCode' of undefined

### ISSUE THREAD

**Issue by landland** [arunoda/meteor-apm-client#3]
Another very cool project from you, Arunoda. Thought I would give the early project a try. I have an method that tries to load a map. The map won't load after instaling apm and here is the error message:

> I20140127-01:38:59.739(0)? Exception while invoking method 'getAddress' TypeError: Cannot read property 'statusCode' of
> undefined
> I20140127-01:38:59.741(0)?     at Object.HTTP.call (packages/apm/lib/hijack/http.js:6)
> I20140127-01:38:59.742(0)?     at Meteor.methods.getAddress (app/server/methods.js:42:8)
> I20140127-01:38:59.746(0)?     at maybeAuditArgumentChecks (packages/livedata/livedata_server.js:1349)
> I20140127-01:38:59.747(0)?     at packages/livedata/livedata_server.js:569
> I20140127-01:38:59.749(0)?     at _.extend.withValue (packages/meteor/dynamics_nodejs.js:35)
> I20140127-01:38:59.753(0)?     at packages/livedata/livedata_server.js:568
> I20140127-01:38:59.757(0)?     at _.extend.withValue (packages/meteor/dynamics_nodejs.js:35)
> I20140127-01:38:59.758(0)?     at DDPServer._CurrentWriteFence.withValue (packages/apm/lib/hijack/wrap_session.js:120)
> I20140127-01:38:59.760(0)?     at _.extend.protocol_handlers.method (packages/livedata/livedata_server.js:567)
> I20140127-01:38:59.761(0)?     at sessionProto.protocol_handlers.method (packages/apm/lib/hijack/wrap_session.js:54)

Here's the method

```
getAddress: function (address) {
  check(address, String);
  this.unblock();
  var Future = Npm.require("fibers/future");
  var fut    = new Future();
  HTTP.call("GET", "http://maps.googleapis.com/maps/api/geocode/json",
   {params: {address: address, sensor: false}},
   function (error, result) {
    if (result.statusCode === 200) {
      fut['return'](result.content);
    }    
  });  
  return fut.wait();
}
```

**Comment by arunoda** [comment]
Thanks. I can work on that.
BTW: You don't need to pass the callback, you can directly get the response
without the callback.
Like, var response = HTTP.call('GET', ...);

On Mon, Jan 27, 2014 at 7:22 AM, landland notifications@github.com wrote:

> Another very cool project from you, Arunoda. Thought I would give the
> early project a try. I have an method that tries to load a map. The map
> won't load after instaling apm and here is the error message:
> 
> I20140127-01:38:59.739(0)? Exception while invoking method 'getAddress'
> TypeError: Cannot read property 'statusCode' of
> undefined
> I20140127-01:38:59.741(0)? at Object.HTTP.call
> (packages/apm/lib/hijack/http.js:6)
> I20140127-01:38:59.742(0)? at Meteor.methods.getAddress
> (app/server/methods.js:42:8)
> I20140127-01:38:59.746(0)? at maybeAuditArgumentChecks
> (packages/livedata/livedata_server.js:1349)
> I20140127-01:38:59.747(0)? at packages/livedata/livedata_server.js:569
> I20140127-01:38:59.749(0)? at _.extend.withValue
> (packages/meteor/dynamics_nodejs.js:35)
> I20140127-01:38:59.753(0)? at packages/livedata/livedata_server.js:568
> I20140127-01:38:59.757(0)? at _.extend.withValue
> (packages/meteor/dynamics_nodejs.js:35)
> I20140127-01:38:59.758(0)? at DDPServer._CurrentWriteFence.withValue
> (packages/apm/lib/hijack/wrap_session.js:120)
> I20140127-01:38:59.760(0)? at _.extend.protocol_handlers.method
> (packages/livedata/livedata_server.js:567)
> I20140127-01:38:59.761(0)? at sessionProto.protocol_handlers.method
> (packages/apm/lib/hijack/wrap_session.js:54)
> 
> Here's the method
> 
> getAddress: function (address) {
>   check(address, String);
>   this.unblock();
>   var Future = Npm.require("fibers/future");
>   var fut    = new Future();
>   HTTP.call("GET", "http://maps.googleapis.com/maps/api/geocode/json",
>    {params: {address: address, sensor: false}},
>    function (error, result) {
>     if (result.statusCode === 200) {
>       fut['return'](result.content);
>     }
>   });
>   return fut.wait();
> }
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/arunoda/meteor-apm-client/issues/3
> .

## 

Arunoda Susiripala

@arunoda http://twitter.com/arunoda
http://gplus.to/arunodahttps://github.com/arunoda
http://www.linkedin.com/in/arunoda

**Comment by landland** [comment]
Nice, I'll update the method. Thanks!

**Comment by landland** [comment]
Updated the method and the error message is gone.
