### ISSUE TITLE
Horizontal scrollbar at the bottom in Chrome on Windows

### ISSUE THREAD

**Issue by dandv** [arunoda/meteor-apm-client#34]
Happens for viewports wider than 992px. Seems to be caused by the `#wrapper { margin: 0 10px; }` declaration. If I uncheck it in Chrome, the scrollbar goes away.

![image](https://cloud.githubusercontent.com/assets/33569/2953676/c6b49b54-da61-11e3-8993-63bcf0ed4815.png)

**Comment by pahans** [comment]
thanks @dandv for reporting this issue. We have fixed it now.

**Comment by dandv** [comment]
Confirm fixed. Thanks!

**Comment by arunoda** [comment]
Thank You Dan for suggesting us with the fix.

---

Arunoda Susiripala
I curate Meteor Weekly - Check it
out!http://meteorhacks.com/meteor-weekly/?utm_source=email-footer&utm_medium=email&utm_campaign=meteorweekly
