### ISSUE TITLE
Application sharing

### ISSUE THREAD

**Issue by reywood** [arunoda/meteor-apm-client#38]
First off, thanks for making this great product.

It would be great if I could give other users access to the dashboard for one of my APM applications. This would enable others on my dev team to check out the app's stats. As it stands, it looks like I would have to give them my APM username and password. Bonus points if I could assign them a role for the app, such as admin, read-only, etc.

**Comment by arunoda** [comment]
Hi,

application sharing is coming with June 2nd.
With our release.

---

Arunoda Susiripala
I curate Meteor Weekly - Check it
out!http://meteorhacks.com/meteor-weekly/?utm_source=email-footer&utm_medium=email&utm_campaign=meteorweekly

**Comment by reywood** [comment]
Awesome, thanks!
