### ISSUE TITLE
Time is Dec 31st, 4pm

### ISSUE THREAD

**Issue by dandv** [arunoda/meteor-apm-client#40]
Looks like a default timestamp of some sort:

![image](https://cloud.githubusercontent.com/assets/33569/3015280/5c7fd35c-df61-11e3-851a-a68b4d6e3d6c.png)

**Comment by arunoda** [comment]
Interesting. What's the appId. Is this only for traces or for all the data?

On Monday, May 19, 2014, Dan Dascalescu notifications@github.com wrote:

> Looks like a default timestamp of some sort:
> 
> [image: image]https://cloud.githubusercontent.com/assets/33569/3015280/5c7fd35c-df61-11e3-851a-a68b4d6e3d6c.png
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/arunoda/meteor-apm-client/issues/40
> .

## 

---

Arunoda Susiripala
I curate Meteor Weekly - Check it
out!http://meteorhacks.com/meteor-weekly/?utm_source=email-footer&utm_medium=email&utm_campaign=meteorweekly

**Comment by dandv** [comment]
Only for traces. App id is 6kpgrQKaEf52bsb8z

**Comment by arunoda** [comment]
Thanks. In will check this. If possible send me the direct URL of the trace
via an email.

On Monday, May 19, 2014, Dan Dascalescu notifications@github.com wrote:

> Only for traces. App id is 6kpgrQKaEf52bsb8z
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/arunoda/meteor-apm-client/issues/40#issuecomment-43514822
> .

## 

---

Arunoda Susiripala

@arunoda http://twitter.com/arunoda
http://gplus.to/arunodahttps://github.com/arunoda
http://www.linkedin.com/in/arunoda

**Comment by dandv** [comment]
Confirmed fixed. Thanks!
