### ISSUE TITLE
Traced subscriptions are hard to find

### ISSUE THREAD

**Issue by dandv** [arunoda/meteor-apm-client#41]
Here's a [video describing the problem](http://screencast.com/t/HbYBohaPPKz). I've learned how to find the traced subscriptions but it can be a bit less intuitive for new users to click in the right spot (blue dot in the top-center of chart spikes).

**Comment by arunoda** [comment]
Yes. You've a valid point. It's hard to find. If we add some bigger dot on
the places where traces exists. That'd be great.
We sent traces, if there is an outlier only, that's why you can't see
traces on every location (in 30min range)

This can be addressed. Will work on this.

---

Arunoda Susiripala
I curate Meteor Weekly - Check it
out!http://meteorhacks.com/meteor-weekly/?utm_source=email-footer&utm_medium=email&utm_campaign=meteorweekly

**Comment by dandv** [comment]
It's sometimes _really_ hard to find traces by looking at the chart:

![image](https://cloud.githubusercontent.com/assets/33569/3130402/8967601c-e7f7-11e3-951f-74a8409b1c31.png)

Maybe the chart and traces should be decoupled,or the traces plotted on the chart as a separate data series consisting of points that launch the trace explorer on click.

**Comment by arunoda** [comment]
This seems like strange. Can you send me the URL page. (may be via an email)

---

Arunoda Susiripala

@arunoda http://twitter.com/arunoda
http://gplus.to/arunodahttps://github.com/arunoda
http://www.linkedin.com/in/arunoda

**Comment by dandv** [comment]
The trace seems to be gone (i.e. there's no trace "4625"), if I look in the Week view at that time range, 5AM - 8AM:

![image](https://cloud.githubusercontent.com/assets/33569/3135786/810f7bc0-e838-11e3-87c7-4e61813634e8.png)

The URL of the PubSub Detailed View is [this](https://ui.meteorapm.com/apps/6kpgrQKaEf52bsb8z/pubsub/detailed-view/content-portfolio?res=3hour&metric=resTime).

**Comment by arunoda** [comment]
May be you could find it with the 24hours view or directly jump to a given
time.

---

Arunoda Susiripala

@arunoda http://twitter.com/arunoda
http://gplus.to/arunodahttps://github.com/arunoda
http://www.linkedin.com/in/arunoda

**Comment by dandv** [comment]
I haven't found it, but here's another one:

https://ui.meteorapm.com/apps/6kpgrQKaEf52bsb8z/pubsub/detailed-view/content-portfolio?date=1401454099540&res=1min&metric=resTime

![image](https://cloud.githubusercontent.com/assets/33569/3135993/eb2b7f56-e83b-11e3-9e49-8d9ccbbb09de.png)

Clicking on the trace goes to https://ui.meteorapm.com/apps/6kpgrQKaEf52bsb8z/pubsub/detailed-view/content-portfolio?explore=58b57759-0931-4ad9-a957-09fd1b52df19&type=pub&date=1401454099540&res=1min&metric=resTime

**Comment by dandv** [comment]
How do I access the 24hours view? Don't see it in the dropdown,

![image](https://cloud.githubusercontent.com/assets/33569/3136005/1f4b3826-e83c-11e3-9fc7-2cf042cc80cf.png)

**Comment by arunoda** [comment]
It's not there Dan. Coming on Monday.

---

Arunoda Susiripala

@arunoda http://twitter.com/arunoda
 http://gplus.to/arunodahttps://github.com/arunoda
http://www.linkedin.com/in/arunoda

**Comment by arunoda** [comment]
Unfortunately, with the current UI you can't find it from the Week since
there are some other traces with higher responseTime.

---

Arunoda Susiripala

@arunoda http://twitter.com/arunoda
http://gplus.to/arunodahttps://github.com/arunoda
http://www.linkedin.com/in/arunoda

**Comment by dandv** [comment]
Closing after moving to Kadira
