### ISSUE TITLE
Guide on not using oplog

### ISSUE THREAD

**Issue by dandv** [arunoda/meteor-apm-client#43]
The guides on reducing network impact and response time are great.

A guide on "not using oplog", maybe even hyperlinked from the trace, would be good too.

![image](https://cloud.githubusercontent.com/assets/33569/3015863/5ce70594-df67-11e3-83d8-d6ebf0d40c84.png)

**Comment by arunoda** [comment]
Hmm.

Good idea.

---

Arunoda Susiripala
I curate Meteor Weekly - Check it
out!http://meteorhacks.com/meteor-weekly/?utm_source=email-footer&utm_medium=email&utm_campaign=meteorweekly

**Comment by dandv** [comment]
https://github.com/meteor/meteor/wiki/Oplog-Observe-Driver would be a good start.

**Comment by dandv** [comment]
A guide would be useful indeed. I've read that meteor wiki post but don't see what applies to my query:

```
collection : content
selector: {"pubDate":{"$gt":"1900-02-01T08:00:00.000Z"},"$or":[{"ct":"article"},{"score":{"$gt":10}}]}
function : observeChanges
isCursorMethod: true
fields: {"body":0}
sort: {"pubDate":-1,"title":1}
limit: 100
oplog: false
noOfHandles: 1
noOfCachedDocs: 100
```

**Comment by arunoda** [comment]
Actually, now Meteor can handle most of the queries (including this one).
Although, let's see if we can work some per query based guide.

---

Arunoda Susiripala

@arunoda http://twitter.com/arunoda
http://gplus.to/arunodahttps://github.com/arunoda
http://www.linkedin.com/in/arunoda

**Comment by dandv** [comment]
Ah, nevermind, I was running the app [in production](https://github.com/meteor/meteor/wiki/Oplog-Observe-Driver#oplogobservedriver-in-production), not with `meteor run`, and didn't have the replica set and oplogger user set up.

**Comment by arunoda** [comment]
Okay.

---

Arunoda Susiripala

@arunoda http://twitter.com/arunoda
 http://gplus.to/arunodahttps://github.com/arunoda
http://www.linkedin.com/in/arunoda

**Comment by dandv** [comment]
Actually, there _is_ a problem after all. I've just run the app with `meteor myapp`, and according to [the docs](https://github.com/meteor/meteor/wiki/Oplog-Observe-Driver), "Oplog tailing is automatically enabled in development mode with `meteor run`". The same query as above doesn't use oplog. Meteor release 0.8.0, Mongo 2.4.10, app id 6kpgrQKaEf52bsb8z.

![image](https://cloud.githubusercontent.com/assets/33569/3016875/2580bb70-df73-11e3-9a27-24c2bb79f877.png)

**Comment by dandv** [comment]
I've enabled oplog by running `mongod --master`. `db.printReplicationInfo()` shows:

> onfigured oplog size: 990MB
> log length start to end: 38196secs (10.61hrs)
> oplog first event time: Fri May 30 2014 05:13:09 GMT-0700 (PDT)
> oplog last event time: Fri May 30 2014 15:49:45 GMT-0700 (PDT)
> now: Fri May 30 2014 15:49:47 GMT-0700 (PDT)

Yet I still see "Not Using Oplog" in APM.

**Comment by dandv** [comment]
Still having the problems above, but moved the [issue to the Kadira repo](https://github.com/meteorhacks/kadira/issues/1).
