### ISSUE TITLE
Zoomable charts / better time granularity

### ISSUE THREAD

**Issue by dandv** [arunoda/meteor-apm-client#55]
HighCharts allows for chart zooming easily. This would enable the user better granularity than 1 week vs. 30 minutes. Maybe I could find [that missing trace](https://github.com/arunoda/meteor-apm-client/issues/41#issuecomment-44696580) that way.

**Comment by arunoda** [comment]
Yes. It's coming. A 24 hour view is coming.

---

Arunoda Susiripala
I curate Meteor Weekly - Check it out!
http://meteorhacks.com/meteor-weekly/?utm_source=email-footer&utm_medium=email&utm_campaign=meteorweekly

**Comment by dandv** [comment]
Closing after moving to Kadira.
