### ISSUE TITLE
Security implications of publishing APM UI URLs

### ISSUE THREAD

**Issue by dandv** [arunoda/meteor-apm-client#56]
Sometimes I was requested to [send a URL to a page privately](https://github.com/arunoda/meteor-apm-client/issues/41#issuecomment-44646630). What are the security implications of posting it publicly? As a general security practice, leaked URLs should not allow a third party to log in or perform much of an attack.

**Comment by arunoda** [comment]
Yep. That stay the same.
With a URL no one can't access to the account without your login info.

---

Arunoda Susiripala
I curate Meteor Weekly - Check it out!
http://meteorhacks.com/meteor-weekly/?utm_source=email-footer&utm_medium=email&utm_campaign=meteorweekly

**Comment by dandv** [comment]
Thanks. Is there a reason then for sending these URLs via email?

**Comment by arunoda** [comment]
Nope. You can give it publicly if you are okay with it :)
Nothing will get leaked. only your appId and may be some of your methodName
and publicationName.

---

Arunoda Susiripala

@arunoda http://twitter.com/arunoda
http://gplus.to/arunodahttps://github.com/arunoda
http://www.linkedin.com/in/arunoda

**Comment by dandv** [comment]
I see, thanks!
